require('plugins.configs.bufferline')
require('plugins.configs.coc')
require('plugins.configs.gitsigns')
require('plugins.configs.lualine')
require('plugins.configs.nvimtree')
require('plugins.configs.treesitter')
